<?php
	include('contents/about.php');
	include('contents/book.php');
	include('contents/contact.php');
	include('contents/facilities.php');
	include('contents/friends.php');
	include('contents/location.php');
	include('contents/news.php');
	include('contents/rooms.php');
?>